"""add narrative generation tables

Revision ID: 4e33c3458933
Revises: 7df74618732c
Create Date: 2026-07-12 18:28:39.991600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4e33c3458933'
down_revision: Union[str, None] = '7df74618732c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narrative_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('narrative_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('baseline_project_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comparison_project_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('missing_narrative_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_contract_version', sa.String(length=32), nullable=False),
    sa.Column('payload_schema_version', sa.String(length=32), nullable=False),
    sa.Column('validator_version', sa.String(length=32), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('regenerated_from_generation_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regenerated_from_generation_id'], ['narrative_generations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_narrative_generations_project_id_input_hash', 'narrative_generations', ['project_id', 'input_hash'], unique=False)
    op.create_index('ix_narrative_generations_project_id_status', 'narrative_generations', ['project_id', 'status'], unique=False)
    op.create_table('narrative_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generation_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('narrative_type', sa.String(length=64), nullable=True),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.String(length=64), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('comparison_value', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('related_brand', sa.String(length=255), nullable=True),
    sa.Column('related_topic', sa.String(length=64), nullable=True),
    sa.Column('related_publication', sa.String(length=500), nullable=True),
    sa.Column('related_story_key', sa.Text(), nullable=True),
    sa.Column('related_article_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('caveat', sa.Text(), nullable=True),
    sa.Column('raw_candidate', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['narrative_generations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_narrative_insights_generation_id_validation_status', 'narrative_insights', ['generation_id', 'validation_status'], unique=False)
    op.create_index('ix_narrative_insights_project_id', 'narrative_insights', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_narrative_insights_project_id', table_name='narrative_insights')
    op.drop_index('ix_narrative_insights_generation_id_validation_status', table_name='narrative_insights')
    op.drop_table('narrative_insights')
    op.drop_index('ix_narrative_generations_project_id_status', table_name='narrative_generations')
    op.drop_index('ix_narrative_generations_project_id_input_hash', table_name='narrative_generations')
    op.drop_table('narrative_generations')
    # ### end Alembic commands ###
