"""add uploaded_files and articles tables

Revision ID: 77890b2bbc2a
Revises: 1a392762921e
Create Date: 2026-07-12 08:33:33.063952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '77890b2bbc2a'
down_revision: Union[str, None] = '1a392762921e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=1000), nullable=False),
    sa.Column('retailer_hint', sa.String(length=64), nullable=True),
    sa.Column('detected_retailer', sa.String(length=64), nullable=True),
    sa.Column('workbook_sheet', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('valid_row_count', sa.Integer(), nullable=False),
    sa.Column('invalid_row_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_row_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uploaded_files_project_id', 'uploaded_files', ['project_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_file_id', sa.UUID(), nullable=False),
    sa.Column('original_row_number', sa.Integer(), nullable=False),
    sa.Column('retailer', sa.String(length=64), nullable=False),
    sa.Column('medium', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('article_url', sa.Text(), nullable=True),
    sa.Column('mediatrust_url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('audience', sa.Float(), nullable=True),
    sa.Column('ave', sa.Float(), nullable=True),
    sa.Column('sentiment_original', sa.String(length=64), nullable=True),
    sa.Column('importance_original', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('county', sa.String(length=128), nullable=True),
    sa.Column('source_audience', sa.Float(), nullable=True),
    sa.Column('subfolder_1', sa.String(length=255), nullable=True),
    sa.Column('subfolder_2', sa.String(length=255), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_article_id', sa.UUID(), nullable=True),
    sa.Column('import_status', sa.String(length=16), nullable=False),
    sa.Column('import_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_articles_fingerprint', 'articles', ['fingerprint'], unique=False)
    op.create_index('ix_articles_project_id', 'articles', ['project_id'], unique=False)
    op.create_index('ix_articles_project_id_fingerprint', 'articles', ['project_id', 'fingerprint'], unique=False)
    op.create_index('ix_articles_uploaded_file_id', 'articles', ['uploaded_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_uploaded_file_id', table_name='articles')
    op.drop_index('ix_articles_project_id_fingerprint', table_name='articles')
    op.drop_index('ix_articles_project_id', table_name='articles')
    op.drop_index('ix_articles_fingerprint', table_name='articles')
    op.drop_table('articles')
    op.drop_index('ix_uploaded_files_project_id', table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
