"""add classification tables

Revision ID: 7df74618732c
Revises: 77890b2bbc2a
Create Date: 2026-07-12 10:16:38.894351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7df74618732c'
down_revision: Union[str, None] = '77890b2bbc2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classification_batches_project_id', 'classification_batches', ['project_id'], unique=False)
    op.create_index('ix_classification_batches_project_id_status', 'classification_batches', ['project_id', 'status'], unique=False)
    op.create_table('classification_batch_articles',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['batch_id'], ['classification_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', 'article_id')
    )
    op.create_index('ix_classification_batch_articles_article_id', 'classification_batch_articles', ['article_id'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('primary_topic', sa.String(length=64), nullable=False),
    sa.Column('secondary_topic', sa.String(length=64), nullable=True),
    sa.Column('communication_category', sa.String(length=64), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('brand_role', sa.String(length=32), nullable=False),
    sa.Column('story_key', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale_ro', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_index('ix_classifications_project_id', 'classifications', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classifications_project_id', table_name='classifications')
    op.drop_table('classifications')
    op.drop_index('ix_classification_batch_articles_article_id', table_name='classification_batch_articles')
    op.drop_table('classification_batch_articles')
    op.drop_index('ix_classification_batches_project_id_status', table_name='classification_batches')
    op.drop_index('ix_classification_batches_project_id', table_name='classification_batches')
    op.drop_table('classification_batches')
    # ### end Alembic commands ###
