"""add chat tables

Revision ID: 93fab4c29c23
Revises: 4e33c3458933
Create Date: 2026-07-12 22:26:41.367170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '93fab4c29c23'
down_revision: Union[str, None] = '4e33c3458933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('baseline_project_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comparison_project_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('scope_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_sessions_project_id', 'chat_sessions', ['project_id'], unique=False)
    op.create_index('ux_chat_sessions_scope_key', 'chat_sessions', ['scope_key'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_session_id_created_at', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('chat_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_message_id', sa.UUID(), nullable=False),
    sa.Column('retry_of_run_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan_request_hash', sa.String(length=64), nullable=True),
    sa.Column('answer_request_hash', sa.String(length=64), nullable=True),
    sa.Column('planning_payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer_payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_call_count', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_type', sa.String(length=20), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_brand', sa.String(length=255), nullable=True),
    sa.Column('related_topic', sa.String(length=64), nullable=True),
    sa.Column('related_publication', sa.String(length=500), nullable=True),
    sa.Column('related_story_key', sa.Text(), nullable=True),
    sa.Column('related_article_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_contract_version', sa.String(length=32), nullable=False),
    sa.Column('payload_schema_version', sa.String(length=32), nullable=False),
    sa.Column('validator_version', sa.String(length=32), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retry_of_run_id'], ['chat_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_runs_session_id_status', 'chat_runs', ['session_id', 'status'], unique=False)
    op.create_index('ux_chat_runs_active_per_session', 'chat_runs', ['session_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'running')"))
    # chat_messages.run_id -> chat_runs.id is added here, after chat_runs
    # exists, to break the chat_messages <-> chat_runs circular dependency
    # (autogenerate does not split a use_alter=True constraint into its own
    # ALTER TABLE — it has to be done explicitly).
    op.create_foreign_key(
        'fk_chat_messages_run_id', 'chat_messages', 'chat_runs', ['run_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chat_messages_run_id', 'chat_messages', type_='foreignkey')
    op.drop_index('ux_chat_runs_active_per_session', table_name='chat_runs', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_index('ix_chat_runs_session_id_status', table_name='chat_runs')
    op.drop_table('chat_runs')
    op.drop_index('ix_chat_messages_session_id_created_at', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ux_chat_sessions_scope_key', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_project_id', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
